{% set name = "gt-coar-lab" %}
{% set version = "2.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - path: ../../labextensions.txt
  - path: ../../LICENSE
  - path: ../../postBuild

build:
  noarch: python
  number: 0
  script: "cd {{ RECIPE_DIR }} && {{ PYTHON }} postBuild"

requirements:
  host:
    - python
    - pip
    - nodejs >=12,<13.0.0a0
    - jupyterlab =={{ version }}
  run:
    - python
    - jupyterlab =={{ version }}

test:
  commands:
    - jupyter labextension list

about:
  home: https://github.com/gt-coar/gt-coar-lab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A pre-built JupyterLab to support interactive reinforcement learning'
