#!/usr/bin/env python3
# Copyright (c) 2020 University System of Georgia and GTCOARLab Contributors
# Distributed under the terms of the BSD-3-Clause License
from subprocess import check_call
from pathlib import Path

HERE = Path(__file__).parent


def _(args, **kwargs):
    """ a little wrapper to handle Paths for windows, and echoing
    """
    str_args = [str(a) for a in args]

    print("\n{}\n".format(" ".join(str_args)))

    if "cwd" in kwargs:
        kwargs["cwd"] = str(kwargs["cwd"])

    return check_call(args, **kwargs)


LABEXTENSIONS = sorted([
    ext.strip()
    for ext in (HERE / "labextensions.txt").read_text().strip().splitlines()
    if ext.strip() and not ext.startswith("#")
])

_(["jupyter", "labextension", "install", "--debug", "--no-build", *LABEXTENSIONS])
_(["jupyter", "lab", "build", "--debug", "--dev-build=False", "--minimize=True"])
