# Copyright (c) 2020 University System of Georgia and GTCOARLab Contributors
# Distributed under the terms of the BSD-3-Clause License

name: core
channels: []
dependencies:
  # gym and friends
  - gym
  - gym-box2d
  - gym-atari
  # interactive computing extensions
  - jupyterlab >=3.0.6
  - jupyterlab-git
  - dask_labextension
  - importnb
  - jupyter_bokeh
  # collaboration and presentation
  - jupyter-videochat
  - ipydrawio
  # numerical compute
  - numpy
  - pandas
  # differentiable compute
  - dask
  - distributed
  - pytorch
  - swifter
  - tensorflow
  # interactive visualization
  - datashader
  - hvplot
  - ipycytoscape
  - ipyelk
  - ipywidgets >=7.6,<8
  - py2cytoscape
  - python-graphviz
  # code assistance
  - jupyterlab-lsp
  - jupyter-lsp-python-plugins
  - jupyter-lsp-latex
  # computer algebra
  - antlr-python-runtime >=4.7,<4.8
  - sympy
  # network manipulation
  - networkx
  # benchmarking
  - asv
  # computer vision
  - py-opencv
  - scikit-image
  # testing
  - pytest
  - pytest-asyncio
  # headless rendering
  - pyopengl
  - pyopengl-accelerate
  # pins from audit
  - rsa >=4.3
