# Copyright (c) 2020 University System of Georgia and GTCOARLab Contributors
# Distributed under the terms of the BSD-3-Clause License

name: qa

channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nodefaults

dependencies:
  - black
  - flake8
  - isort >=5
  - nbformat
  - pytest
  - robotframework-lint >=1.1
  - yamllint
