# Copyright (c) 2020 University System of Georgia and GTCOARLab Contributors
# Distributed under the terms of the BSD-3-Clause License

name: rl-lab-base

channels:
  - anaconda

dependencies:
  - anaconda-project ==0.8.3
  - python >=3.7,<3.8.0a0
