# Copyright (c) 2020 University System of Georgia and GTCOARLab Contributors
# Distributed under the terms of the BSD-3-Clause License

name: gt-coar-lab-base

channels:
  - https://repo.anaconda.com/pkgs/main

dependencies:
  - anaconda-project ==0.8.4
  - python >=3.7,<3.8.0a0
  - doit
