# Copyright (c) 2021 University System of Georgia and GTCOARLab Contributors
# Distributed under the terms of the BSD-3-Clause License

name: gt-coar-lab-dev

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - graphviz2drawio
  - ipydrawio-export
  - ipyelk
  - jupyterlab >=3,<4
  - jupyterlab-gt-coar-theme >=0.2.4
  - qrcode-artistic-svg
