# 2020 University System of Georgia and GTCOARLab Contributors
# Distributed under the terms of the BSD-3-Clause License

channels:
  - https://repo.anaconda.com/pkgs/main
  - https://conda.anaconda.org/conda-forge
dependencies:
  - antlr-python-runtime >=4.7,<4.8
  - asv
  - conda >=4.8.3,<4.9.0a0
  - conda-build >=3.11,<3.18.0a0
  - conda-pack
  - conda-verify
  - constructor >=3.0.2,<3.1.0a0
  - dask
  - dask_labextension
  - datashader
  - distributed
  - firefox =68
  - geckodriver
  - git
  - gym
  - gym-atari
  - gym-box2d
  - hvplot
  - importnb
  - ipywidgets
  - jupyterlab ==2.1.3
  - jupyterlab-git
  - jupyterlab_server ==1.1.5
  - networkx
  - nodejs >=12,<13.0.0a0
  - numpy
  - pandas
  - py-opencv
  - pyopengl
  - pyopengl-accelerate
  - pytest
  - pytest-asyncio
  - python >=3.7,<3.8.0a0
  - pytorch-cpu
  - pyvirtualdisplay
  - ripgrep
  - robotframework
  - robotframework-seleniumlibrary
  - scikit-image
  - sympy
  - tensorflow
name: gt-coar-lab
