#!/usr/bin/env bash
set -eux
rm -rf ${NB_PYTHON_PREFIX}
conda create --prefix ${NB_PYTHON_PREFIX} --file cpu-linux-64.conda.lock
source deactivate
source ${NB_PYTHON_PREFIX}/bin/activate
jupyter lab clean --all
jupyter labextension install --debug --no-build $(cat labextensions.txt)
jupyter lab build --debug --dev-build=False --minimize=True
