name: Build Installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: >-
            ${{ runner.os }}
            -conda
            -${{ env.CACHE_NUMBER }}
            -${{ hashFiles('.ci_support/environment-base.yml') }}
      - uses: goanpeca/setup-miniconda@v1.4.1
        with:
          activate-environment: rl-lab-base
          environment-file: .ci_support/environment-base.yml
          auto-activate-base: false
          use-only-tar-bz2: true
      - shell: bash -l {0}
        run: |
          anaconda-project run yarn
          anaconda-project run lint
          git diff || echo "no changes made"

  construct:
    name: Build ${{ matrix.os }}
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.4.1
        with:
          activate-environment: rl-lab-base
          environment-file: .ci_support/environment-base.yml
          auto-activate-base: false
      - shell: bash -l {0}
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          anaconda-project run build
      - shell: cmd /C CALL {0}
        if: ${{ contains(matrix.os, 'windows') }}
        run: >-
          anaconda-project run build
