# yamllint disable rule:truthy

name: Build Installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.4.1
        with:
          activate-environment: rl-lab-base
          environment-file: .ci_support/environment-base.yml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          anaconda-project run yarn
          anaconda-project run lint
          git diff || echo "no changes made"
  conda_lab:
    name: conda lab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.4.1
        with:
          activate-environment: rl-lab-base
          environment-file: .ci_support/environment-base.yml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          anaconda-project run build conda_lab
      - name: upload gt-coar-lab conda package
        uses: actions/upload-artifact@v2
        with:
          name: conda-gt-coar-lab
          path: dist/conda-bld

  construct:
    name: Build ${{ matrix.os }}
    needs:
      - lint
      - conda_lab
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: download gt-coar-lab conda package
        uses: actions/download-artifact@v2
        with:
          name: conda-gt-coar-lab
      - uses: goanpeca/setup-miniconda@v1.4.1
        with:
          activate-environment: rl-lab-base
          environment-file: .ci_support/environment-base.yml
          auto-activate-base: false
      - shell: bash -l {0}
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          anaconda-project run build template installer
      - shell: cmd /C CALL {0}
        if: ${{ contains(matrix.os, 'windows') }}
        run: >-
          anaconda-project run build template installer
      - name: upload installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: dist/installers
