name: Build Installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  jobs:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.4.1
        with:
          activate-environment: rl-lab-base
          environment-file: .ci_support/environment-base.yml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          anaconda-project run yarn
          anaconda-project run lint

  construct:
    name: ${{ matrix.os }}
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.4.1
        with:
          activate-environment: rl-lab-base
          environment-file: .ci_support/environment-base.yml
          auto-activate-base: false
      - shell: bash -l {0}
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          anaconda-project run build
      - shell: cmd /C CALL {0}
        if: ${{ contains(matrix.os, 'windows') }}
        run: >-
          anaconda-project run build
